features:
  top_n: 14

split:
  test_size: 0.2
  random_state: 42

logistic_regression:
  max_iter: 1000
  C: [0.01, 0.1, 1, 10]
  penalty: ['l2']
  solver: ['liblinear', 'lbfgs']

random_forest:
  n_estimators: [50, 100, 150]
  max_depth: [null, 10, 20, 30]
  min_samples_split: [2, 5]
  min_samples_leaf: [1, 2]

svm:
  C: [0.1, 1, 10]
  kernel: ["linear", "rbf", "poly"]
  gamma: ["scale", "auto"]

knn:
  n_neighbors: [3, 5, 7, 9]
  weights: ['uniform', 'distance']
  metric: ['euclidean', 'manhattan']

gradient_boosting:
  n_estimators: [50, 100, 150]
  learning_rate: [0.1, 0.05, 0.01]
  max_depth: [3, 5, 7]
  subsample: [1.0, 0.8]
